In [1]:
import numpy as np

In [9]:
arr = np.array([[1,2,4],[7,13,21]])

In [11]:
print(arr)

[[ 1  2  4]
 [ 7 13 21]]


In [12]:
print("Shape : ", arr.shape)

Shape :  (2, 3)


In [15]:
n_rows = 2
n_columns = 3
arr2 = np.random.random((n_rows,n_columns))

In [16]:
print(arr2)

[[0.93796746 0.54478742 0.58912106]
 [0.00773798 0.39284777 0.40818447]]


In [20]:
zero_arr = np.zeros((4,5,2))

In [21]:
print(arr3)

[[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]]


In [22]:
ones_arr = np.ones((4,5,2))

In [23]:
print(ones_arr)

[[[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]]


In [24]:
y = np.array([[1, 2, 3],
              [4, 5, 6]])

In [26]:
y.ndim

2

In [27]:
y.shape

(2, 3)

In [32]:
y_transpose = y.reshape(3,2)

In [33]:
print(y_transpose)

[[1 2]
 [3 4]
 [5 6]]


In [34]:
y_flat = y.reshape(6,1)

In [35]:
print(y_flat)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
